# Generated by Django 4.2.3 on 2023-07-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('appetizers', 'appetizers'), ('entrees', 'entrees'), ('treats', 'treats')], max_length=60),
        ),
    ]
